[build]
  command = "make build"
  publish = "out"
  functions = "functions"

[dev]
  publish = "out"
  functions = "functions"

[template.environment]
  NODE_ENV=""
  PRISMIC_REPO_NAME=""
  PRISMIC_ACCESS_TOKEN=""
  STRIPE_PUBLISHABLE_KEY=""
  STRIPE_SECRET_KEY=""
