[build]
  command = "make build"
  publish = "out"
  functions = "pages/api"

[dev]
  publish = "out"
  functions = "pages/api"

[template.environment]
  NODE_ENV=""
  PRISMIC_REPO_NAME=""
  PRISMIC_ACCESS_TOKEN=""
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=""
  STRIPE_SECRET_KEY=""
