name: Run pa11y-ci on preview URLs

on: [deployment_status]

jobs:
  pa11y:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm install --include=dev
      - run: pa11y-ci --sitemap ${{ github.event.deployment_status.target_url }}/sitemap.xml
