name: tests

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  deployment_status:
    state: [success]

jobs:
  pa11y:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm install -g pa11y-ci
      - run: pa11y-ci --sitemap ${{ github.event.deployment_status.target_url }}/sitemap.xml
